- id: 200
  key: satoshi
  currency: btc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 400
  key: bank
  currency: brl
  sort_order: 2
  bank_accounts:
    -
      bank: 'Your Bank Name'
      branch: 'Your Bank Branch'
      holder: 'Your Account Holder'
      account: 'Your Account Number'
- id: 600
  key: doge
  currency: doge
  min_confirm: 9
  max_confirm: 10
- id: 800
  key: ltc
  currency: ltc
  min_confirm: 9
  max_confirm: 10
- id: 1000
  key: spero
  currency: spero
  min_confirm: 9
  max_confirm: 10
- id: 1200
  key: mxt
  currency: mxt
  min_confirm: 199
  max_confirm: 200
- id: 1400
  key: rvn
  currency: rvn
  min_confirm: 20
  max_confirm: 30
- id: 1600
  key: da
  currency: da
  min_confirm: 25
  max_confirm: 50
- id: 1800
  key: ac
  currency: ac
  min_confirm: 25
  max_confirm: 50
- id: 2000
  key: ep
  currency: ep
  min_confirm: 25
  max_confirm: 50
- id: 2200
  key: ad
  currency: ad
  min_confirm: 5
  max_confirm: 10
- id: 2400
  key: bd
  currency: bd
  min_confirm: 25
  max_confirm: 50
- id: 2600
  key: hb
  currency: hb
  min_confirm: 25
  max_confirm: 50
- id: 2800
  key: am
  currency: am
  min_confirm: 25
  max_confirm: 50
- id: 3000
  key: at
  currency: at
  min_confirm: 25
  max_confirm: 50
- id: 3200
  key: fz
  currency: fz
  min_confirm: 25
  max_confirm: 50
- id: 3400
  key: ew
  currency: ew
  min_confirm: 25
  max_confirm: 50
- id: 3600
  key: an
  currency: an
  min_confirm: 25
  max_confirm: 50
- id: 3800
  key: fj
  currency: fj
  min_confirm: 25
  max_confirm: 50
- id: 4000
  key: ba
  currency: ba
  min_confirm: 10
  max_confirm: 50
